metropolis_website/charts/urls.py
# from views import input_metropolis_parameters
from django.contrib import admin
from django.urls import path, include
from charts import views

app_name = 'charts'

urlpatterns = [
    path('', views.index, name='index'),
    path('input/', views.input_metropolis_parameters, name='input-metropolis-parameters'),
    path('delete/', views.delete_record, name='delete-record'),
    path('plots/', views.MetropolisPlotListView.as_view(), name='metropolisplots'),
    path('plots/<int:pk>', views.MetropolisPlotDetailView.as_view(), name='metropolisplot-detail'),
    path('plots/<int:pk>/view', views.plot_view, name='plot-view')
]

metropolis_website/metropolis_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from charts import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='charts/', permanent=False)),
    path('api', views.ChartData.as_view()),
    path('input', views.DataInput.as_view()),
    path('api_plot/<int:pk>', views.plot_api)
]

urlpatterns += [
    path('charts/', include('charts.urls'))
]

metropolis_website/charts/models.py
from django.db import models
from django.urls import reverse

# # Create your models here.

class MetropolisPlot(models.Model):
    DISTRIBUTIONS = (
        ('norm', 'Normal Distribution'),
        ('unif', 'Uniform Distribution')
    )

    dist = models.CharField(choices=DISTRIBUTIONS, help_text='Enter desired distribution', max_length=4)
    bins = models.IntegerField(help_text='Enter desired number of points in distribution')
    totSamples = models.IntegerField(help_text='Enter the desired number of drawn samples')
    mean = models.DecimalField(decimal_places=3, max_digits=6, help_text='Enter the mean of the distribution', default=0)
    std = models.DecimalField(decimal_places=3, max_digits=6, help_text='Enter the standard devaition of the distribution', default=1)
    lowerBound = models.DecimalField(decimal_places=3, max_digits=6, help_text='Enter a lower bound')
    upperBound = models.DecimalField(decimal_places=3, max_digits=6, help_text='Enter an upper bound')

    def get_absolute_url(self):
        """Returns the url to access a detail record for this choice of parameters."""
        return reverse('charts:metropolisplot-detail', args=[str(self.id)])

    def get_plot_view(self, *args):
        """Returns the url to access the plots for the given record."""
        # Currently redirects to itself #
        return reverse('charts:input_metropolis_parameters', args=[str(self.id)])

metropolis_website/charts/forms.py
from django import forms
from django.core.exceptions import ValidationError

class MetropolisParameters(forms.Form):
    DISTRIBUTIONS=[('norm', 'Normal Distribution'),
                   ('unif', 'Uniform Distribution')]

    dist = forms.ChoiceField(choices=DISTRIBUTIONS)
    bins = forms.IntegerField()
    totSamples = forms.IntegerField()
    mean = forms.DecimalField()
    std = forms.DecimalField()
    lowerBound = forms.DecimalField()
    upperBound = forms.DecimalField()

    def clean_metropolis_parameters(self):
        data = self.cleaned_data['dist', 'bins', 'totSamples', 'mean', 'std', 'lowerBound', 'upperBound']

        if data['dist'] not in ['norm', 'unif']:
            raise ValidationError('Invalid Distribution')
        if data['bins'] < 2:
            raise ValidationError('Invalid Number of Points')
        if data['totSamples'] < 1:
            raise ValidationError('Invalid Number of Samples')
        if data['std'] <= 0:
            raise ValidationError('Invalid Standard Deviation')
        if data['lowerBound'] >= data['upperBound']:
            raise ValidationError('Invalid Bounds')
        if data['upperBound'] <= data['lowerBound']:
            raise ValidationError('Invalid Bounds')

        return data

class MetropolisDelete(forms.Form):
    id = forms.IntegerField()

    def clean_metropolis_delete(self):
        data = self.cleaned_data['id']

        return data

metropolis_website/charts/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import render, get_object_or_404
from django.views import generic
from django.views.generic import View, FormView
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse

from charts.forms import MetropolisParameters, MetropolisDelete
from .models import MetropolisPlot

from rest_framework.views import APIView
from rest_framework.response import Response

import numpy as np
import scipy.stats
from numpy import ndarray, random
from collections import defaultdict

# Create your views here.

class MetropolisPlotListView(generic.ListView):
    model = MetropolisPlot

class MetropolisPlotDetailView(generic.DetailView):
    model = MetropolisPlot

class DataInput(FormView):
    form = MetropolisParameters
    template = 'charts/input.html'

    def get_success_url(self):
        return ''

    def form_valid(self, form):
        return super().form_valid(form)

    def input_data(self, request):
        if request.method == 'POST':
            form = MetropolisParameters(request.POST)
            if form.is_valid:
                return HttpResponseRedirect('')
        else:
            form = MetropolisParameters()

        return render(request, 'charts/input.html', {'form': form})

class HomeView(View):
    def get(self, request, *args, **kwargs):
        return render(request, 'charts/index.html')

class ChartData(APIView):

    def get_prob_dist_func(leftBound, rightBound, numPoints, mean, std, distribution='norm'):
        data_points = np.linspace(leftBound, rightBound, numPoints) # Create array of evenly spaced points that include left and right bound
        try:
            if distribution=='norm':
                pdf = [scipy.stats.norm.pdf(point, loc=mean, scale=std)/numPoints for point in data_points] # Create a normal distribution from data_points
            elif distribution=='unif':
                pdf = [scipy.stats.uniform.pdf(point)/numPoints for point in data_points] # Create a uniform distribution from data_points
        except:
            print('Invalid distribution') 

        return pdf, ndarray.tolist(data_points)


    def get_markov_chain(pdf, numPoints, tot_samples):

        start_idx = random.randint(0, numPoints) # Select random starting index of data array
        markov_idx = [start_idx]                   # Initialize list of markov indicies
        count = 0

        for i in range(tot_samples):
            coin = random.randint(0,2)
            if coin:
                if markov_idx[count] == len(pdf) - 1:                     # check if the chain can go any more to the right
                    markov_idx.append(markov_idx[count])                  # append current value to chain
                elif pdf[markov_idx[count] + 1] > pdf[markov_idx[count]]: # check if prob to the right is greater
                    markov_idx.append(markov_idx[count] + 1)              # append index of prob to the right
                else:
                    if random.rand() < (pdf[markov_idx[count] + 1] / pdf[markov_idx[count]]): # probabilistically decide to go to the right
                        markov_idx.append(markov_idx[count] + 1)                              # append index of prob to the right
                    else:
                        markov_idx.append(markov_idx[count])                                  # append current index
            else:
                if markov_idx[count] == 0:                                # check if the chain can go any more to the left
                    markov_idx.append(markov_idx[count])                  # append current value to chain
                elif pdf[markov_idx[count] - 1] > pdf[markov_idx[count]]: # check if prob to the left is greater
                    markov_idx.append(markov_idx[count] - 1)              # append index of prob to the right
                else:
                    if random.rand() < (pdf[markov_idx[count] - 1] / pdf[markov_idx[count]]): # probabilistically decide to go to the left
                        markov_idx.append(markov_idx[count] - 1)                              # append index of prob to the left
                    else:
                        markov_idx.append(markov_idx[count])                                  #  append current index

            count += 1

        return markov_idx


    def get_freq(markov_idx):
        fq = defaultdict(int)
        for i in markov_idx:
            fq[i] += 1

        fq = dict(fq)       # Create dictionary with key value pairs consisting of markov indices and their corresponding frequencies
        
        indices = sorted(fq.keys())
        frequencies = [value for (key, value) in sorted(fq.items())]

        return indices, frequencies


    def get(self, request, format = None):

        pdf_chartdata, pdf_temp_labels = ChartData.get_prob_dist_func(-3, 3, 41, 'norm')
        pdf_labels = [round(label, 3) for label in pdf_temp_labels]
        pdf_chartLabel = 'Probability Distribution'
        pdf_data = {
            'labels':pdf_labels,
            'chartLabel':pdf_chartLabel,
            'chartdata':pdf_chartdata,
        }

        mc_chartdata = ChartData.get_markov_chain(pdf_chartdata, len(pdf_labels))
        mc_chartLabel = 'Markov Chain'
        mc_labels = list(range(len(mc_chartdata)))
        mc_data = {
            'labels':mc_labels,
            'chartLabel':mc_chartLabel,
            'chartdata':mc_chartdata
        }

        bar_labels, bar_chartdata = ChartData.get_freq(mc_chartdata)
        bar_chartLabel = 'Markov Histogram'
        bar_data = {
            'labels':bar_labels,
            'chartLabel':bar_chartLabel,
            'chartdata':bar_chartdata
        }

        data = [pdf_data, mc_data, bar_data]
        return Response(data)

def index(request):
    """View function for home page of site."""
    num_plots = MetropolisPlot.objects.all().count()

    context = {
        'num_plots': num_plots,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

def input_metropolis_parameters(request):

    if request.method == 'POST':
        form = MetropolisParameters(request.POST)
        if form.is_valid():
            form.dist = form.cleaned_data['dist']
            form.bins = form.cleaned_data['bins']
            form.totSamples = form.cleaned_data['totSamples']
            form.mean = form.cleaned_data['mean']
            form.std = form.cleaned_data['std']
            form.lowerBound = form.cleaned_data['lowerBound']
            form.upperBound = form.cleaned_data['upperBound']
            plot = MetropolisPlot(dist=form.dist, bins=form.bins, totSamples=form.totSamples, mean=form.mean, std=form.std,
                                  lowerBound=form.lowerBound, upperBound=form.upperBound)
            plot.save()
        
    else:
        form = MetropolisParameters()

    return render(request, 'charts/metropolisplot_input.html', {'form': form})

def delete_record(request):
    if request.method == 'POST':
        form = MetropolisDelete(request.POST)
        if form.is_valid():
            form.id = form.cleaned_data['id']
            try:
                plot = MetropolisPlot(id=form.id)
            except:
                raise ValidationError('ID does not exist')
            plot.delete()
        
    else:
        form = MetropolisDelete()
    
    return render(request, 'charts/metropolisplot_delete.html', {'form': form})

def plot_api(request, pk):

    obj = MetropolisPlot.objects.get(pk=pk)

    mean = float(obj.mean)
    std = float(obj.std)
    lowerBound = float(obj.lowerBound)
    upperBound = float(obj.upperBound)

    pdf_chartdata, pdf_temp_labels = ChartData.get_prob_dist_func(lowerBound, upperBound, obj.bins, mean, std, obj.dist)
    pdf_labels = [round(label, 3) for label in pdf_temp_labels]
    pdf_chartLabel = 'Probability Distribution'
    pdf_data = {
        'labels':pdf_labels,
        'chartLabel':pdf_chartLabel,
        'chartdata':pdf_chartdata,
    }

    mc_chartdata = ChartData.get_markov_chain(pdf_chartdata, len(pdf_labels), tot_samples=obj.totSamples)
    mc_chartLabel = 'Markov Chain'
    mc_labels = list(range(len(mc_chartdata)))
    mc_data = {
        'labels':mc_labels,
        'chartLabel':mc_chartLabel,
        'chartdata':mc_chartdata
    }

    bar_labels, bar_chartdata = ChartData.get_freq(mc_chartdata)
    bar_chartLabel = 'Markov Histogram'
    bar_data = {
        'labels':bar_labels,
        'chartLabel':bar_chartLabel,
        'chartdata':bar_chartdata
    }

    data = [pdf_data, mc_data, bar_data]

    return JsonResponse(data, safe=False)

def plot_view(request, pk):
    context = {'pk': pk}

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'charts/plot_view.html', context=context)

metropolis_website/charts/templates/charts/metropolisplot_delete.html
{% extends "base_generic.html" %}

{% block content %}
<h2>Enter ID of Plot to be Deleted</h2></br>
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <p><input type="submit" value="Submit" onclick="deletionSuccess()"></p>
</form>

<script>
    function deletionSuccess() {
        alert('Deletion Successful')
    }
</script>
{% endblock %}

metropolis_website/charts/templates/charts/metropolisplot_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>ID: {{ metropolisplot.id }}</h1>

  <p><strong>Distribution: </strong>{{ metropolisplot.dist }}</p>
  <p><strong>Number of Distribution Points: </strong>{{ metropolisplot.bins }}</p>
  <p><strong>Number of Samples: </strong>{{ metropolisplot.totSamples }}</p>
  <p><strong>Mean: </strong>{{ metropolisplot.mean }}</p>
  <p><strong>Standard Deviation: </strong>{{ metropolisplot.std }}</p>
  <p><strong>Lower Bound: </strong>{{ metropolisplot.lowerBound }}</p>
  <p><strong>Upper Bound: </strong>{{ metropolisplot.upperBound }}</p>
  <a href="{% url 'charts:plot-view' metropolisplot.id %}">View plot</a>

{% endblock %}

metropolis_website/charts/templates/charts/metropolisplot_input.html
{% extends "base_generic.html" %}

{% block content %}
<h2>Enter Parameters</h2></br>
<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <p><input type="submit" value="Submit" onclick="submissionSuccess()"></p>
</form>

<script>
    function submissionSuccess() {
        alert('Input Successful')
    }
</script>
{% endblock %}

metropolis_website/charts/templates/charts/metropolisplot_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Plot List</h1>
  {% if metropolisplot_list %}
  <ul>
    {% for metropolisplot in metropolisplot_list %}
      <li>
        <a href="{{ metropolisplot.get_absolute_url }}">{{ metropolisplot.id }}</a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no plots available.</p>
  {% endif %}
{% endblock %}

metropolis_website/charts/templates/charts/metropolisplot_view.html
{% extends "base_generic.html" %}

{% block content %}
  <p>Distribution: {{ metropolisplot.dist }}</p>
  <p>Lower Bound: {{ metropolisplot.lowerBound }}</p>
  <p>Upper Bound: {{ metropolisplot.upperBound }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

metropolis_website/charts/templates/charts/plot_view.html
<!DOCTYPE html>
<html lang='en' dir='ltr'>

<head>
    <meta charset='utf-8'>
    <title>charts</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

</head>

<body class='container-fluid'>
    <center class="row">
        <h1>Implementation of <b>chartJS</b> using <b>django</b></h1>
    </center>
    <hr />
    <div class='row'>
        <div class='col-md-6'>
            <canvas id='myChartline'></canvas>
        </div>
        <div class='col-md-6'>
            <canvas id='myChartMarkov'></canvas>
        </div>
        <div class='col-md-6'>
            <canvas id='myChartBar'></canvas>
        </div>
    </div>
    
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>

    <script>
        var endpoint = '/api_plot/{{ pk }}';

        $.ajax({
            method: 'GET',
            url: endpoint,
            success: function(data) {
                console.log(data)
                drawLineGraph(data[0], 'myChartline');
                drawMarkovGraph(data[1], 'myChartMarkov');
                drawBarGraph(data[2], 'myChartBar');
                console.log('drawing');
            },
            error: function(error_data) {
                console.log(error_data);
            }
        })

        function drawLineGraph(data, id) {
            var labels = data.labels;
            var chartLabel = data.chartLabel;
            var chartdata = data.chartdata;
            var ctx = document.getElementById(id).getContext('2d');
            var chart = new Chart(ctx, {
                // The type of chart we want to create
                type: 'line',

                // The data for our dataset
                data: {
                    labels: labels,
                    datasets: [{
                        label: chartLabel,
                        backgroundColor: 'rgb(55, 99, 132)',
                        borderColor: 'rgb(255, 0, 0)',
                        data: chartdata,
                    }]
                },

                // Configuration options go here
                options: {
                    scales: {
                        xAxes: [{
                            display: true
                        }],
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });
        }

        function drawMarkovGraph(data, id) {
            var labels = data.labels;
            var chartLabel = data.chartLabel;
            var chartdata = data.chartdata;
            var ctx = document.getElementById(id).getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'line',
                data: {
                    labels: labels,
                    datasets: [{
                        label: chartLabel,
                        data: chartdata,
                        // backgroundColor: 'rgb(55, 99, 132)',
                        borderColor: 'rgb(255, 0, 0)',
                        borderWidth: 1
                    }]
                },
                options: {
                    indexAxis: 'y',
                    scales: {
                        xAxes: [{
                            // type: 'logarithmic',
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });
        }


        function drawBarGraph(data, id) {
            var labels = data.labels;
            var chartLabel = data.chartLabel;
            var chartdata = data.chartdata;
            var ctx = document.getElementById(id).getContext('2d');
            var myChart = new Chart(ctx, {
                type: 'bar',
                data: {
                    labels: labels,
                    datasets: [{
                        label: chartLabel,
                        data: chartdata,
                        // backgroundColor: [
                        //     'rgba(255, 99, 132, 0.2)',
                        //     'rgba(54, 162, 235, 0.2)',
                        //     'rgba(255, 206, 86, 0.2)',
                        //     'rgba(75, 192, 192, 0.2)',
                        //     'rgba(153, 102, 255, 0.2)',
                        //     'rgba(255, 159, 64, 0.2)'
                        // ],
                        // borderColor: [
                        //     'rgba(255, 99, 132, 1)',
                        //     'rgba(54, 162, 235, 1)',
                        //     'rgba(255, 206, 86, 1)',
                        //     'rgba(75, 192, 192, 1)',
                        //     'rgba(153, 102, 255, 1)',
                        //     'rgba(255, 159, 64, 1)'
                        // ],
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                }
            });
        }
    </script>
</body>

</html>